import Head from 'next/head';
import Link from 'next/link';
import { toast } from 'react-hot-toast';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Blog App - Fireabse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link
          prefetch={false}
          href={{ pathname: '/[username]', query: { username: 'diego123' } }}
        >
          Diego&apos;s profile
        </Link>
        <button onClick={() => toast.success('Great!')}>Toast</button>
      </div>
    </>
  );
}
